apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
id: counter-app
metadata:
  name: counter app v2
  description: A basic counter
  version: 2.0.0
  catalog:
    organization:
      - name: nhat-14
        site: https://github.com/nhat-14
deploymentProfiles:
  - type: compose
    id: counter-app-compose
    components:
      - name: counter-app
        properties:
          packageLocation: https://raw.githubusercontent.com/nhat-14/counter-edge-app/refs/heads/main/src/compose-v2.yaml