apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
id: counter-app
metadata:
  name: counter app
  description: A basic counter
  version: 1.0.0
  catalog:
    organization:
      - name: nhat-14
        site: https://github.com/nhat-14
deploymentProfiles:
  - type: compose
    id: counter-app-compose
    components:
      - name: counter-app
        properties:
          packageLocation: https://github.com/nhat-14/counter-edge-app/blob/main/src/compose.yaml